from . import clg_student
from . import clg_department
from . import clg_add
from . import check
from . import payment_wizard
from . import payment_invoice
from . import schedule_action
from . import professor
from . import clg_subject
from . import general_information
